from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

from rich.console import Console
from rich.table import Table

from .automation import run_once, upload_existing_package
from .config import load_settings, load_strategy
from .growth import finalize_metadata
from .llm import NvidiaChatClient
from .models import TrendItem, UploadMetadata, VideoPlan
from .policy import evaluate_plan
from .renderer import render_video
from .research import build_research_bundle
from .scriptwriter import create_video_plan
from .secure_bot import SecureBotError, SecureTelegramBot
from .telegram_bot import TelegramBotError, TelegramController
from .trends import collect_news_for_query, collect_trends
from .utils import jaccard, read_json, slugify, utc_now_slug, write_json
from .youtube import UploadDisabled, authorize_youtube, upload_video


console = Console()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="viralforge",
        description="Discover trends, create original animated videos, and optionally upload to YouTube.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    discover = subparsers.add_parser("discover", help="Show currently discovered trend candidates.")
    discover.add_argument("--limit", type=int, default=12)
    discover.set_defaults(func=cmd_discover)

    run = subparsers.add_parser("run", help="Create a video package from a trend or explicit topic.")
    run.add_argument("--topic", default="", help="Use an explicit topic instead of auto-selecting a trend.")
    run.add_argument("--trend-limit", type=int, default=20)
    run.add_argument("--no-render", action="store_true", help="Generate scripts and metadata without rendering MP4.")
    run.add_argument("--upload", action="store_true", help="Upload after rendering. Requires YouTube OAuth and passing compliance.")
    run.add_argument("--force-upload", action="store_true", help="Allow upload even if compliance audit has flags.")
    run.set_defaults(func=cmd_run)

    autopilot = subparsers.add_parser(
        "autopilot",
        help="Run the full automation loop one or more times with duplicate-topic memory.",
    )
    autopilot.add_argument("--count", type=int, default=1, help="Number of videos to create in this session.")
    autopilot.add_argument("--interval-minutes", type=float, default=0.0, help="Delay between runs when count is above 1.")
    autopilot.add_argument("--topic", default="", help="Optional fixed topic for the first run.")
    autopilot.add_argument("--trend-limit", type=int, default=24)
    autopilot.add_argument("--no-render", action="store_true", help="Generate plan and metadata only.")
    autopilot.add_argument("--upload", action="store_true", help="Upload after rendering. OAuth must already be linked.")
    autopilot.add_argument("--force-upload", action="store_true", help="Allow upload even if compliance audit has flags.")
    autopilot.set_defaults(func=cmd_autopilot)

    auth = subparsers.add_parser("youtube-auth", help="Open OAuth once and link the YouTube upload token.")
    auth.set_defaults(func=cmd_youtube_auth)

    telegram = subparsers.add_parser("telegram-bot", help="Run the Telegram control bot.")
    telegram.set_defaults(func=cmd_telegram_bot)

    secure_bot = subparsers.add_parser("secure-bot", help="Run the advanced secure Telegram bot.")
    secure_bot.set_defaults(func=cmd_secure_bot)

    upload = subparsers.add_parser("upload", help="Upload an existing rendered video package.")
    upload.add_argument("--video", required=True)
    upload.add_argument("--metadata", required=True, help="Path to metadata.json generated by run.")
    upload.add_argument("--force", action="store_true", help="Bypass local compliance package check.")
    upload.set_defaults(func=cmd_upload)

    audit = subparsers.add_parser("audit", help="Audit an existing plan/research package.")
    audit.add_argument("--plan", required=True)
    audit.add_argument("--research", required=True)
    audit.set_defaults(func=cmd_audit)

    args = parser.parse_args(argv)
    return args.func(args)


def cmd_discover(args: argparse.Namespace) -> int:
    settings = load_settings()
    strategy = load_strategy(settings)
    trends = collect_trends(settings, strategy, limit=args.limit)
    write_json(settings.outputs_dir / "latest_trends.json", [trend.to_dict() for trend in trends])
    _print_trends(trends)
    console.print(f"\nSaved: {settings.outputs_dir / 'latest_trends.json'}")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    settings = load_settings()
    strategy = load_strategy(settings)
    try:
        package = run_once(
            settings,
            strategy,
            topic=args.topic,
            trend_limit=args.trend_limit,
            render=not args.no_render,
            upload=args.upload,
            force_upload=args.force_upload,
        )
    except Exception as exc:
        console.print(f"[red]{type(exc).__name__}: {exc}[/red]")
        return 2
    _print_package(
        package.output_dir,
        package.plan,
        package.compliance.to_dict(),
        package.rendered,
        package.upload_result,
    )
    return 0


def cmd_autopilot(args: argparse.Namespace) -> int:
    settings = load_settings()
    strategy = load_strategy(settings)
    count = max(1, args.count)
    interval_seconds = max(0.0, args.interval_minutes) * 60
    for index in range(count):
        topic = args.topic if index == 0 else ""
        console.print(f"\n[bold cyan]Autopilot run {index + 1}/{count}[/bold cyan]")
        try:
            package = run_once(
                settings,
                strategy,
                topic=topic,
                trend_limit=args.trend_limit,
                render=not args.no_render,
                upload=args.upload,
                force_upload=args.force_upload,
            )
        except Exception as exc:
            console.print(f"[red]{type(exc).__name__}: {exc}[/red]")
            return 2
        _print_package(
            package.output_dir,
            package.plan,
            package.compliance.to_dict(),
            package.rendered,
            package.upload_result,
        )
        if index < count - 1 and interval_seconds:
            console.print(f"[dim]Sleeping {args.interval_minutes:g} minute(s) before the next run...[/dim]")
            time.sleep(interval_seconds)
    return 0


def cmd_youtube_auth(args: argparse.Namespace) -> int:
    settings = load_settings()
    try:
        result = authorize_youtube(settings)
    except FileNotFoundError as exc:
        console.print(f"[red]{exc}[/red]")
        return 2
    except Exception as exc:
        console.print(f"[red]{type(exc).__name__}: {exc}[/red]")
        return 3
    console.print("[bold green]YouTube OAuth token linked[/bold green]")
    console.print(f"Token: {result['token_file']}")
    console.print(f"Scopes: {', '.join(result['scopes'])}")
    return 0


def cmd_telegram_bot(args: argparse.Namespace) -> int:
    settings = load_settings()
    strategy = load_strategy(settings)
    try:
        TelegramController(settings, strategy).run_forever()
    except TelegramBotError as exc:
        console.print(f"[red]{exc}[/red]")
        return 2
    except KeyboardInterrupt:
        console.print("\n[yellow]Telegram bot stopped.[/yellow]")
        return 0


def cmd_secure_bot(args: argparse.Namespace) -> int:
    settings = load_settings()
    strategy = load_strategy(settings)
    try:
        SecureTelegramBot(settings, strategy).run_forever()
    except SecureBotError as exc:
        console.print(f"[red]{exc}[/red]")
        return 2
    except KeyboardInterrupt:
        console.print("\n[yellow]Secure bot stopped.[/yellow]")
        return 0


def cmd_upload(args: argparse.Namespace) -> int:
    settings = load_settings()
    try:
        result = upload_existing_package(settings, Path(args.video), Path(args.metadata))
    except UploadDisabled as exc:
        console.print(f"[red]{exc}[/red]")
        return 2
    console.print(result)
    return 0


def cmd_audit(args: argparse.Namespace) -> int:
    from .models import ResearchBundle, ResearchSource

    settings = load_settings()
    strategy = load_strategy(settings)
    plan = VideoPlan.from_dict(read_json(Path(args.plan)))
    research_data = read_json(Path(args.research))
    bundle = ResearchBundle(
        topic=research_data.get("topic", plan.topic),
        angle=research_data.get("angle", plan.angle),
        sources=[ResearchSource(**source) for source in research_data.get("sources", [])],
        notes=research_data.get("notes", []),
    )
    report = evaluate_plan(plan, bundle, strategy)
    _print_report(report.to_dict())
    return 0 if report.passed else 1


def _related_items(topic: str, trends: list[TrendItem]) -> list[TrendItem]:
    if not trends:
        return []
    ranked = sorted(trends, key=lambda item: jaccard(topic, item.title) + item.score / 20, reverse=True)
    selected = [item for item in ranked if jaccard(topic, item.title) > 0.08]
    if not selected and ranked:
        selected = ranked[:4]
    return selected[:6]


def _print_trends(trends: list[TrendItem]) -> None:
    table = Table(title="Trend Candidates")
    table.add_column("#", justify="right", style="cyan", no_wrap=True)
    table.add_column("Score", justify="right")
    table.add_column("Source")
    table.add_column("Title")
    for index, trend in enumerate(trends, start=1):
        table.add_row(str(index), f"{trend.score:.2f}", trend.source, trend.title)
    console.print(table)


def _print_report(report: dict) -> None:
    color = "green" if report["passed"] else "yellow"
    console.print(f"[{color}]Compliance passed: {report['passed']} | risk: {report['risk_score']}[/{color}]")
    for flag in report.get("flags", []):
        console.print(f" - {flag}")
    for recommendation in report.get("recommendations", [])[:4]:
        console.print(f" * {recommendation}")


def _print_package(
    output_dir: Path,
    plan: VideoPlan,
    report: dict,
    rendered: dict[str, Path | None],
    upload_result: dict | None,
) -> None:
    console.print("\n[bold green]Video package created[/bold green]")
    console.print(f"Folder: {output_dir}")
    console.print(f"Title: {plan.metadata.title}")
    console.print(f"Hashtags: {' '.join(plan.metadata.hashtags)}")
    _print_report(report)
    if rendered.get("video"):
        console.print(f"Video: {rendered['video']}")
    if rendered.get("thumbnail"):
        console.print(f"Thumbnail: {rendered['thumbnail']}")
    if rendered.get("nvidia_videos"):
        nvidia_videos = rendered["nvidia_videos"]
        console.print(f"NVIDIA Videos: {len(nvidia_videos)} scene(s) generated")
        for scene_id, path in nvidia_videos.items():
            console.print(f"  - {scene_id}: {path}")
    if rendered.get("google_videos"):
        google_videos = rendered["google_videos"]
        console.print(f"Google Veo Videos: {len(google_videos)} scene(s) generated")
        for scene_id, path in google_videos.items():
            console.print(f"  - {scene_id}: {path}")
    if upload_result:
        console.print(f"Uploaded: {upload_result['url']}")


if __name__ == "__main__":
    sys.exit(main())
