from __future__ import annotations

from typing import Any


SKILL_REGISTRY: dict[str, dict[str, Any]] = {
    "cold_open": {
        "category": "storytelling",
        "story": "start with immediate mystery before explanation",
        "edit": "impact_cut",
        "camera": "dolly_push_in",
        "lighting": {"key_light": "low mysterious teal", "rim_light": "thin cyan edge"},
        "vfx": ["bass_hit_flash", "floating_particles"],
        "sfx": ["low_boom"],
        "voice": "mysterious",
        "shot_types": ["establishing", "hero_closeup"],
        "events": ["cold_open_impact"],
        "prompt": "Cold-open impact, immediate mystery, viewer enters mid-moment.",
        "scores": {"emotional_impact": 3, "retention": 3, "cinematic_feel": 2},
    },
    "hero_reveal": {
        "category": "camera",
        "camera": "orbit_reveal",
        "lighting": {"rim_light": "strong cyan hero rim", "background_light": "gold reveal pulse"},
        "vfx": ["lens_flare", "energy_pulse", "volumetric_beams", "hologram_glow"],
        "sfx": ["rising_hit", "soft_boom"],
        "voice": "confident",
        "shot_types": ["hero_closeup", "impact_reveal"],
        "events": ["vfx_reveal"],
        "prompt": "Hero reveal, rim light, particles, lens flare, controlled awe.",
        "scores": {"visual_richness": 3, "cinematic_feel": 3, "narrative_clarity": 1},
    },
    "danger_alert": {
        "category": "lighting",
        "camera": "impact_shake",
        "lighting": {"key_light": "red warning strobe", "rim_light": "cold cyan emergency edge"},
        "vfx": ["red_flash", "glitch", "alarm_particles", "electric_arcs", "warning_pulse"],
        "sfx": ["bass_hit", "glitch"],
        "voice": "warning",
        "shot_types": ["impact_reveal", "ui_macro", "vault_cutaway"],
        "events": ["sound_drop", "pattern_interrupt"],
        "prompt": "Danger alert, red warning light, glitch pulse, urgent high tension.",
        "scores": {"emotional_impact": 3, "retention": 3, "cinematic_feel": 2},
        "incompatible": ["soft_empathy"],
    },
    "caption_punch": {
        "category": "editing",
        "edit": "beat_synced_text_reveal",
        "vfx": ["caption_glow", "underline_swipe"],
        "sfx": ["digital_click", "click_pop"],
        "events": ["text_punch_zoom"],
        "prompt": "Few words only, center-weighted kinetic caption, power words hit on beat.",
        "scores": {"retention": 3, "narrative_clarity": 2},
    },
    "glitch_transition": {
        "category": "editing",
        "edit": "glitch_transition",
        "transition": "glitch_cut",
        "vfx": ["glitch", "chromatic_aberration", "distortion_pulse"],
        "sfx": ["glitch", "whoosh"],
        "events": ["screen_glitch"],
        "prompt": "Fast glitch transition with one-frame distortion and hard audio tick.",
        "scores": {"retention": 2, "visual_richness": 2},
    },
    "montage_burst": {
        "category": "editing",
        "edit": "montage_burst",
        "camera": "over_shoulder_pan",
        "vfx": ["motion_blur", "streak_lines", "spark_hits"],
        "sfx": ["tech_scan", "whoosh"],
        "shot_types": ["fast_montage", "task_cutaway", "ui_macro"],
        "events": ["fast_montage"],
        "prompt": "Fast montage burst, task cards and UI details cut rapidly but stay readable.",
        "scores": {"retention": 3, "visual_richness": 2},
    },
    "safe_control": {
        "category": "storytelling",
        "story": "show control and consequences, not blind hype",
        "camera": "rack_focus_pan",
        "lighting": {"key_light": "clean teal interface glow", "rim_light": "gold approval edge"},
        "vfx": ["shield_pulse", "audit_scan", "clean_glow"],
        "sfx": ["click_pop", "tech_scan"],
        "voice": "confident",
        "shot_types": ["over_shoulder", "shield_cutaway"],
        "prompt": "Human control, audit logs, permission shield, clear safety logic.",
        "scores": {"narrative_clarity": 3, "cinematic_feel": 1},
    },
    "contrast_cut": {
        "category": "storytelling",
        "story": "cut between risky and controlled versions of the same idea",
        "edit": "contrast_cut",
        "vfx": ["split_screen_divide", "light_sweep"],
        "sfx": ["whoosh"],
        "shot_types": ["over_shoulder", "text_impact"],
        "prompt": "Contrast cut: one side chaotic, one side controlled, visual meaning without reading.",
        "scores": {"narrative_clarity": 3, "retention": 2},
    },
    "epic_cta": {
        "category": "storytelling",
        "camera": "final_hero_lock",
        "lighting": {"key_light": "gold key light", "rim_light": "strong cyan heroic outline"},
        "vfx": ["glow", "floating_particles", "volumetric_beams", "lens_flare"],
        "sfx": ["final_hit", "soft_boom"],
        "voice": "direct",
        "shot_types": ["final_hero", "hero_closeup"],
        "events": ["hero_cta"],
        "prompt": "Epic CTA, low-angle hero hold, digital key floating toward viewer.",
        "scores": {"emotional_impact": 2, "retention": 2, "cinematic_feel": 3},
    },
    "cinematic_world_depth": {
        "category": "lighting",
        "lighting": {
            "background_light": "deep moving server glow",
            "atmosphere": "volumetric fog beams and dust",
        },
        "vfx": ["depth_fog", "floating_particles", "volumetric_beams"],
        "prompt": "Layered foreground, midground, background, fog, particles, visible light source.",
        "scores": {"visual_richness": 3, "cinematic_feel": 3},
    },
    "nvidia_video": {
        "category": "external_video",
        "external_provider": "nvidia",
        "vfx": ["nvidia_cosmos_reference"],
        "prompt": "Package this scene for NVIDIA Cosmos text-to-video generation with camera motion, lighting, and continuity constraints.",
        "scores": {"visual_richness": 3, "cinematic_feel": 3},
        "max_per_video": 3,
    },
    "seedance2_prompt_package": {
        "category": "external_video",
        "external_provider": "seedance2",
        "vfx": ["seedance2_motion_reference"],
        "prompt": "Package this scene as a Seedance 2 style text-to-video prompt with camera, lighting, VFX, action, and continuity constraints.",
        "scores": {"visual_richness": 3, "cinematic_feel": 3},
        "max_per_video": 3,
    },
}


PURPOSE_SKILL_RULES = {
    "hook": ["cold_open", "hero_reveal", "caption_punch", "cinematic_world_depth"],
    "problem": ["montage_burst", "caption_punch", "cinematic_world_depth"],
    "reveal": ["hero_reveal", "caption_punch", "cinematic_world_depth", "nvidia_video"],
    "warning": ["danger_alert", "glitch_transition", "caption_punch", "cinematic_world_depth", "nvidia_video"],
    "cta": ["epic_cta", "caption_punch", "cinematic_world_depth", "nvidia_video"],
}


def get_skill(skill_id: str) -> dict[str, Any]:
    return SKILL_REGISTRY[skill_id]
